import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Comfortaa } from "next/font/google";

const azonix = localFont({
  src: [
    {
      path: "../public/fonts/Azonix.otf",
    },
  ],
  variable: "--font-azonix",
});


const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${azonix.variable} ${comfortaa.variable}`}>{children}</body>
    </html>
  );
}
